Repository 2024TUKCOMSP/IWant100, pull requests merged in 2024-07, with the labels that each got.

#35 feat : make project
  IWant100_BE/.gitignore
  IWant100_BE/build.gradle
  IWant100_BE/gradle/wrapper/gradle-wrapper.jar
  IWant100_BE/gradle/wrapper/gradle-wrapper.properties
  IWant100_BE/gradlew
  IWant100_BE/gradlew.bat
  IWant100_BE/settings.gradle
  IWant100_BE/src/main/java/IWant100/IWant100_BE/IWant100BeApplication.java
  IWant100_BE/src/main/resources/application.properties
  IWant100_BE/src/test/java/IWant100/IWant100_BE/IWant100BeApplicationTests.java
Labels: ✨ Feature

#37 feat : connect DB
  IWant100_BE/.gitignore
  IWant100_BE/build.gradle
  IWant100_BE/src/main/resources/application.properties
Labels: ⚙️ Setting

#39 feat: setting
  IWant100_FE/index.html
  IWant100_FE/package-lock.json
  IWant100_FE/package.json
  IWant100_FE/public/logo.svg
  IWant100_FE/src/App.css
  IWant100_FE/src/App.jsx
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/login/LoginPage.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/tailwind.config.cjs
Labels: ✨ Feature, ⚙️ Setting, 🎨 Html&css

#40 Feat : SaveVote
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/SaveVoteBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteItemDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/SaveVoteDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/SaveVoteItemsDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/Vote.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/VoteItem.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteItemRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteService.java
Labels: ✨ Feature

#42 feat: mainPage
  IWant100_FE/package-lock.json
  IWant100_FE/package.json
  IWant100_FE/src/assets/create_icon.svg
  IWant100_FE/src/assets/profile_icon.svg
  IWant100_FE/src/assets/tino.svg
  IWant100_FE/src/assets/vote_icon.svg
  IWant100_FE/src/components/main/MainPage.jsx
Labels: ✨ Feature, 🎨 Html&css

#43 feat: create vote page
  IWant100_FE/package-lock.json
  IWant100_FE/package.json
  IWant100_FE/public/icons/Google-removebg-preview.svg
  IWant100_FE/public/icons/add.svg
  IWant100_FE/public/icons/back-arrow.svg
  IWant100_FE/public/icons/delete.svg
  IWant100_FE/public/icons/drop-down.svg
  IWant100_FE/public/icons/login-lock.svg
  IWant100_FE/public/icons/select-option.svg
  IWant100_FE/public/icons/submit.svg
  IWant100_FE/public/images/default-header.svg
  IWant100_FE/public/images/login-header.svg
  IWant100_FE/src/App.jsx
  IWant100_FE/src/assets/fonts/esamanru_OTF(Mac)/esamanru OTF Bold.otf
  IWant100_FE/src/assets/fonts/esamanru_OTF(Mac)/esamanru OTF Light.otf
  IWant100_FE/src/assets/fonts/esamanru_OTF(Mac)/esamanru OTF Medium.otf
  IWant100_FE/src/assets/fonts/esamanru_TTF(Win)/esamanru Bold.ttf
  IWant100_FE/src/assets/fonts/esamanru_TTF(Win)/esamanru Light.ttf
  IWant100_FE/src/assets/fonts/esamanru_TTF(Win)/esamanru Medium.ttf
  IWant100_FE/src/components/Header.jsx
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/create/InputBox.jsx
  IWant100_FE/src/components/create/VoteItem.jsx
  IWant100_FE/src/css/esamanru.css
  IWant100_FE/src/index.css
  IWant100_FE/tailwind.config.cjs
Labels: ✨ Feature, 🎨 Html&css

#44 Feat : Get VoteAll
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetVotesBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVotesDTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoteItemTop1DAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVotesDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteGetDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteItemRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteService.java
Labels: ✨ Feature

#45 Feat : Get Vote
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetVoteBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteDTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoteTop1DAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteService.java
Labels: ✨ Feature

#47 Feat : Save User
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/SaveUserBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/small/CreateUserDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/small/SaveUserDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/UserController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/domain/DTO/RequestUserSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/domain/UserDAO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/repository/UserRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/service/UserService.java
Labels: ✨ Feature

#48 Fix: main page
  IWant100_FE/package-lock.json
  IWant100_FE/src/App.jsx
  IWant100_FE/src/components/list/VoteListPage.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/src/components/user/UserPage.jsx
Labels: ✨ Feature, 🔨Refactor

#49 feat: vote list page
  IWant100_FE/src/assets/search.svg
  IWant100_FE/src/components/list/ListHeader.jsx
  IWant100_FE/src/components/list/SearchInputBox.jsx
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/list/VoteListPage.jsx
Labels: ✨ Feature, 🎨 Html&css

#50 feat: user page
  IWant100_FE/src/assets/blue_back.svg
  IWant100_FE/src/components/user/MyList.jsx
  IWant100_FE/src/components/user/UserHeader.jsx
  IWant100_FE/src/components/user/UserPage.jsx
  IWant100_FE/src/components/user/UserProfile.jsx
Labels: ✨ Feature, 🎨 Html&css

#51 feat: result page
  IWant100_FE/src/App.jsx
  IWant100_FE/src/assets/home_icon.svg
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/result/ResultHeader.jsx
  IWant100_FE/src/components/result/ResultItem.jsx
  IWant100_FE/src/components/result/ResultPage.jsx
  IWant100_FE/src/components/result/VoteTitle.jsx
Labels: ✨ Feature, 🎨 Html&css, 🔨Refactor

#52 Feat/login page
  IWant100_FE/src/components/login/LoginPage.jsx
  IWant100_FE/tailwind.config.cjs
Labels: ✨ Feature, 🎨 Html&css

#56 feat : get user
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/GetUserBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/small/CreateUserBTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/small/GetUserDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/UserController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/domain/DTO/ResponseUserGetDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/service/UserService.java
Labels: ✨ Feature

#58 Feat : Get MyVoteAll
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetMyVotesBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVotesDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteService.java
Labels: ✨ Feature

#59 Feat : Save VoteContent
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/SaveVoteContentBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteContentDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/SaveVoterDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteContentController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteContentSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/Voter.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/others/ListConverter.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoterRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteContentService.java
Labels: ✨ Feature

#60 Feat : Get VoteContent
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetVoteContentBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteContentDTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoteDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoterDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteContentController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteContentGetDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteItemGetDto.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoterRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteContentService.java
Labels: ✨ Feature

#61 Feat : Get VoteResult
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetVoteContentResultBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteContentResultDTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteContentController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteContentResultGetDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteItemCountGetDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/service/VoteContentService.java
Labels: ✨ Feature

#62 fix : delete isAnoymous field
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/Vote.java
Labels: 🐞 BugFix

#65 style: modify layout
  IWant100_FE/index.html
  IWant100_FE/public/images/login-header.svg
  IWant100_FE/src/App.jsx
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/list/VoteListPage.jsx
  IWant100_FE/src/components/login/LoginPage.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/src/components/result/ResultItem.jsx
  IWant100_FE/src/components/result/ResultPage.jsx
  IWant100_FE/src/components/user/MyList.jsx
  IWant100_FE/src/components/user/UserPage.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
  IWant100_FE/src/index.css
  IWant100_FE/tailwind.config.cjs
Labels: 🎨 Html&css, 🔨Refactor

#66 fix: font style error
  IWant100_FE/src/components/create/InputBox.jsx
  IWant100_FE/src/components/result/VoteTitle.jsx
  IWant100_FE/src/components/vote/VoteItem.jsx
  IWant100_FE/src/css/esamanru.css
  IWant100_FE/src/index.css
Labels: 🐞 BugFix

#67 fix: remove anonymous option
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: 🐞 BugFix

#68 feat: vote calendar
  IWant100_FE/package-lock.json
  IWant100_FE/package.json
  IWant100_FE/src/components/create/CustomCalendar.jsx
  IWant100_FE/src/components/create/InputBox.jsx
Labels: ✨ Feature, 🎨 Html&css

#70 feat: vote page use api
  IWant100_FE/package-lock.json
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/create/CustomCalendar.jsx
  IWant100_FE/src/components/create/InputBox.jsx
  IWant100_FE/src/components/result/VoteTitle.jsx
  IWant100_FE/src/components/vote/VoteItem.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: ✨ Feature

#69 Feat : GoggleLogin
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/small/GetUserDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/UserController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/repository/UserRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/service/LoginService.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/controller/VoteContentController.java
  IWant100_BE/src/main/resources/application.properties
Labels: ✨ Feature

#71 Fix : Vote-Empty
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetMyVotesBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/GetVotesBean.java
Labels: 🐞 BugFix

#72 Feat : Add Email Field
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/domain/UserDAO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/service/LoginService.java
Labels: 🐞 BugFix, ✨ Feature

#73 Feat/api integration
  IWant100_FE/package-lock.json
  IWant100_FE/package.json
  IWant100_FE/src/components/list/SearchInputBox.jsx
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/list/VoteListPage.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/src/components/user/MyList.jsx
  IWant100_FE/src/components/user/UserPage.jsx
  IWant100_FE/src/components/user/UserProfile.jsx
Labels: ✨ Feature, 📬 API

#74 Fix : GetUser
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/bean/small/CreateUserBTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/domain/DTO/ResponseUserGetDTO.java
Labels: 🐞 BugFix

#76 Feat/result api integration
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/src/components/result/ResultItem.jsx
  IWant100_FE/src/components/result/VoteTitle.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: ✨ Feature, 📬 API, 🔨Refactor

#78 fix: end date format
  IWant100_FE/.gitignore
  IWant100_FE/src/App.jsx
  IWant100_FE/src/components/create/CustomCalendar.jsx
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/login/LoginCallback.jsx
  IWant100_FE/src/components/login/LoginPage.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#80 feat: use env file
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/src/components/result/ResultItem.jsx
  IWant100_FE/src/components/result/VoteTitle.jsx
  IWant100_FE/src/components/user/MyList.jsx
  IWant100_FE/src/components/user/UserProfile.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: ✨ Feature, 📬 API, 🔨Refactor

#81 Feat/create vote page api
  IWant100_FE/src/components/Header.jsx
  IWant100_FE/src/components/create/CreateVoteItem.jsx
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/create/InputBox.jsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 📬 API, 🔨Refactor

#84 feat: use api vote page
  IWant100_FE/src/components/vote/VoteItem.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#90 fix: select end date save error
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/create/CustomCalendar.jsx
Labels: 🐞 BugFix

#92 fix: calc end date error
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/list/VoteList.jsx
Labels: 🐞 BugFix, ✨ Feature

#93 fix : add voteItemContent
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteContentResultDTOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteContentResultGetDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/ResponseVoteItemResultGetDTO.java
Labels: 🐞 BugFix

#94 Fix : Vote
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteItemDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoteItemTop1DAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoteItemsDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVoteTop1DAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/GetVotesDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteItemSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/VoteItem.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteItemRepositoryJPA.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/repository/VoteRepositoryJPA.java
Labels: 🐞 BugFix

#95 style: remove console.log
  IWant100_FE/src/components/user/MyList.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#96 fix : goggleLogin
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix
