Repository 2024TUKCOMSP/IWant100, pull requests merged in 2024-08, with the labels that each got.

#97 Fix : GoggleLogin
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#98 feat: git pages workflow
  .github/workflows/deploy.yml
  IWant100_FE/vite.config.js
Labels: ✨ Feature, 🌏 Deploy

#99 fix: workflow directory error
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#100 fix: workflow error
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#101 fix: search vote
  IWant100_FE/src/components/list/VoteList.jsx
Labels: 🐞 BugFix, 🔨Refactor

#102 fix: remove file and npm install
  .github/workflows/deploy.yml
  IWant100_FE/src/components/login/LoginCallback.jsx
Labels: 🐞 BugFix, 🌏 Deploy

#104 fix: result item
  IWant100_FE/src/components/result/ResultItem.jsx
Labels: 🐞 BugFix, 🔨Refactor

#105 fix: add path, upload artifact step
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#106 fix: add list build directory step
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#108 fix: modify deploy to github pages step
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#109 fix: remove dist folder from .gitignore file
  IWant100_FE/.gitignore
  IWant100_FE/dist/assets/index-BX8zWXvF.css
  IWant100_FE/dist/assets/index-Dps2sQhW.js
  IWant100_FE/dist/assets/tino-CvlE_zmI.svg
  IWant100_FE/dist/icons/Google-removebg-preview.svg
  IWant100_FE/dist/icons/add.svg
  IWant100_FE/dist/icons/back-arrow.svg
  IWant100_FE/dist/icons/delete.svg
  IWant100_FE/dist/icons/drop-down.svg
  IWant100_FE/dist/icons/login-lock.svg
  IWant100_FE/dist/icons/select-option.svg
  IWant100_FE/dist/icons/submit.svg
  IWant100_FE/dist/images/default-header.svg
  IWant100_FE/dist/index.html
  IWant100_FE/dist/logo.svg
  IWant100_FE/dist/vite.svg
Labels: 🐞 BugFix, 🌏 Deploy

#110 fix: upgrade upload pages artifact version
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#111 fix : redirectURL
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#112 fix: workflow
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#113 fix: workflow step
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#114 fix: reset remove code
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#115 fix: path
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#116 fix: change version
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#119 fix: dist
  IWant100_FE/.gitignore
  IWant100_FE/dist/assets/index-BX8zWXvF.css
  IWant100_FE/dist/assets/index-Dps2sQhW.js
  IWant100_FE/dist/assets/tino-CvlE_zmI.svg
  IWant100_FE/dist/icons/Google-removebg-preview.svg
  IWant100_FE/dist/icons/add.svg
  IWant100_FE/dist/icons/back-arrow.svg
  IWant100_FE/dist/icons/delete.svg
  IWant100_FE/dist/icons/drop-down.svg
  IWant100_FE/dist/icons/login-lock.svg
  IWant100_FE/dist/icons/select-option.svg
  IWant100_FE/dist/icons/submit.svg
  IWant100_FE/dist/images/default-header.svg
  IWant100_FE/dist/index.html
  IWant100_FE/dist/logo.svg
  IWant100_FE/dist/vite.svg
Labels: 🐞 BugFix

#120 fix : delete DTO voteItemIndex
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteItemSaveDTO.java
Labels: 🐞 BugFix

#122 fix: redirection url
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteItemDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteItemSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteSaveDTO.java
Labels: 🐞 BugFix

#121 fix : save vote
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/bean/small/CreateVoteItemDAOBean.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteItemSaveDTO.java
  IWant100_BE/src/main/java/IWant100/IWant100_BE/vote/domain/DTO/RequestVoteSaveDTO.java
Labels: 🐞 BugFix

#123 fix: deploy bug
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#124 fix: deploy bug fix
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#125 Fix/deployorigincode
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#126 fix: login error
  IWant100_FE/src/App.jsx
  IWant100_FE/src/components/Header.jsx
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/list/ListHeader.jsx
  IWant100_FE/src/components/list/VoteList.jsx
  IWant100_FE/src/components/login/LoginPage.jsx
  IWant100_FE/src/components/main/MainPage.jsx
  IWant100_FE/src/components/result/ResultHeader.jsx
  IWant100_FE/src/components/user/MyList.jsx
  IWant100_FE/src/components/user/UserHeader.jsx
  IWant100_FE/src/components/user/UserProfile.jsx
  IWant100_FE/src/components/vote/VoteHeader.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
  IWant100_FE/vite.config.js
Labels: 🐞 BugFix, ✨ Feature

#128 fix: deploy
  .github/workflows/deploy.yml
  IWant100_FE/package-lock.json
  IWant100_FE/package.json
  IWant100_FE/vite.config.js
Labels: 🐞 BugFix

#129 fix: google redirection url
  IWant100_FE/src/components/login/LoginPage.jsx
Labels: 🐞 BugFix, 🌏 Deploy

#130 fix: change package file, vite file
  IWant100_FE/package.json
  IWant100_FE/vite.config.js
Labels: 🐞 BugFix, 🌏 Deploy

#131 fix: github pages error
  IWant100_FE/index.html
  IWant100_FE/package.json
  IWant100_FE/src/App.jsx
  IWant100_FE/vite.config.js
Labels: 🐞 BugFix, 🌏 Deploy

#132 fix: deploy error
  IWant100_FE/src/App.jsx
Labels: 🐞 BugFix, 🌏 Deploy

#134 fix: change google login url
  IWant100_FE/src/components/login/LoginPage.jsx
Labels: 🐞 BugFix

#136 fix: login router error
  IWant100_FE/src/components/login/LoginPage.jsx
Labels: 🐞 BugFix, 🌏 Deploy

#137 fix : redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#139 fix : change redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#140 feat: param userId
  IWant100_FE/src/components/result/ResultPage.jsx
Labels: 🐞 BugFix, 🌏 Deploy

#141 fix : change redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#142 Style: change url
  IWant100_FE/src/components/create/CreateVotePage.jsx
  IWant100_FE/src/components/vote/VotePage.jsx
Labels: 🐞 BugFix, 🌏 Deploy

#144 fix : change redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#145 style: homepage change
  IWant100_FE/package.json
Labels: 🐞 BugFix

#146 fix : change redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#147 fix : change redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#149 fix: create vote
  IWant100_FE/src/components/create/CreateVotePage.jsx
Labels: 🐞 BugFix

#150 fix : redirectURI
  IWant100_BE/src/main/java/IWant100/IWant100_BE/user/controller/LoginController.java
Labels: 🐞 BugFix

#151 feat: use firebase
  .gitignore
  IWant100_FE/.firebaserc
  IWant100_FE/dist/assets/index-eOorlRib.css
  IWant100_FE/dist/assets/index-mEA21Vpb.js
  IWant100_FE/dist/index.html
  IWant100_FE/firebase.json
  IWant100_FE/package.json
  IWant100_FE/vite.config.js
Labels: ✨ Feature, 🌏 Deploy
